# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: updateStandingsDB

on: push

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
      - name: create env
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo API_KEY_3=${{ secrets.API_KEY }} >> .env
          cat .env
      - name: Install
        run: npm ci
      - name: Prem
        run: node update-standings/prem.js
