# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: updateStandingsDB

on:
  schedule:
    - cron: '0 12 * * 1' #every monday at 12 (when leagues have finished playing their matchday)

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
      - name: create env
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo API_KEY_3=${{ secrets.API_KEY }} >> .env
          cat .env
      - name: Install
        run: npm ci
      - name: Prem
        run: node update-standings/prem.js
      - name: CPL
        run: node update-standings/cpl.js
      - name: Serie A
        run: node update-standings/serie.js
      - name: Ligue 1
        run: node update-standings/ligue.js
      - name: La Liga
        run: node update-standings/laliga.js
      - name: Bundesliga
        run: node update-standings/bundesliga.js
