# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: updateStandingsDB

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@v3
      - run: node update-standings/prem.js
